<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.payflux</groupId>
	<artifactId>payflux-monorepo</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>

	<name>PayFlux Monorepo</name>
	<description>Payment Orchestration B2B System</description>

	<properties>
		<java.version>21</java.version>
		<spring-boot.version>4.0.6</spring-boot.version>
		<spring-cloud.version>2025.1.1</spring-cloud.version>
		<grpc-core.version>1.81.0</grpc-core.version>
		<grpc-spring-starter.version>3.1.0.RELEASE</grpc-spring-starter.version>
		<protobuf.version>4.34.1</protobuf.version>
		<resilience4j.version>2.2.0</resilience4j.version>
	</properties>

	<modules>
		<module>payment-orchestrator</module>
		<module>merchant-config-service</module>
		<module>webhook-service</module>

		<module>payment-adapters/vnpay-adapter</module>
		<module>payment-adapters/momo-adapter</module>
		<module>payment-adapters/stripe-adapter</module>

		<module>grpc-libs</module>
	</modules>

	<dependencyManagement>
		<dependencies>
			<!-- Spring Boot BOM -->
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>${spring-boot.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<!-- Spring Cloud BOM -->
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-dependencies</artifactId>
				<version>${spring-cloud.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>io.grpc</groupId>
				<artifactId>grpc-bom</artifactId>
				<version>${grpc-core.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
			<dependency>
				<groupId>com.google.protobuf</groupId>
				<artifactId>protobuf-bom</artifactId>
				<version>${protobuf.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
                <groupId>net.devh</groupId>
                <artifactId>grpc-client-spring-boot-starter</artifactId>
                <version>${grpc-spring-starter.version}</version>
            </dependency>
            <dependency>
                <groupId>net.devh</groupId>
                <artifactId>grpc-server-spring-boot-starter</artifactId>
                <version>${grpc-spring-starter.version}</version>
            </dependency>
		</dependencies>
	</dependencyManagement>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
