CREATE USER payflux_app WITH PASSWORD 'user_password';
GRANT CONNECT ON DATABASE payflux_db TO payflux_app;
GRANT USAGE ON SCHEMA public TO payflux_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO payflux_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
      GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO payflux_app;
