spring:
  application:
    name: payment-orchestrator
  config:
    import:
      - "optional:file:./.env[.properties]"
      # - "optional:file:./.env.local[.properties]"
      - "optional:file:./payment-orchestrator/.env[.properties]"
      # - "optional:file:./payment-orchestrator/.env.local[.properties]"
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5678/payflux_db
    username: payflux_app
    password: user_password
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
  data:
    redis:
      host: localhost
      port: 6379
  flyway:
    #    enabled: false
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas:
      - public

mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.payflux.payment_orchestrator.domain
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.payflux.payment_orchestrator.infrastructure.persistence

server:
  port: 8081

grpc:
  client:
    vnpay-adapter:
      address: static://localhost:9101
      negotiation-type: plaintext

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - prometheus

payflux:
  merchants:
    by-consumer-user-name:
      merchant_demo: 11111111-1111-1111-1111-111111111111
  shared:
    web:
      exception-handler-enabled: true
    observability:
      correlation-id-enabled: true
  vnpay:
    hash-secret: ${VNPAY_HASH_SECRET:}

logging:
  level:
    "[net.devh.boot.grpc]": info
    "[org.flywaydb]": info
